# ===================================================================
# Spring Boot configuration.
#
# This configuration will be overridden by the Spring profile you use
# For example: application-dev.yml if you use the "dev" profile.
# ===================================================================

# ===================================================================
# Standard Spring Boot properties.
# Full reference is available at:
# https://docs.spring.io/spring-boot/reference/features/profiles.html
# ===================================================================

logging:
  level:
    root: info
    com.ars.gateway: info
    org.springframework.cloud.gateway: info
    org.springframework.cloud.gateway.filter: info
    org.springframework.web.reactive: info
    reactor.netty: info
  charset:
    console: UTF-8
    file: UTF-8
  # Custom properties to define logs file paths according to different profiles
  file-path: /mnt/logs

spring:
  cloud:
    gateway:
      # Global CORS configuration
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins:
              - "http://localhost:4200"
              - "http://localhost:8080"
            allowedMethods:
              - GET
              - POST
              - PUT
              - PATCH
              - DELETE
              - OPTIONS
            allowedHeaders:
              - Content-Type
              - Authorization
              - Accept
              - Origin
              - X-CSRF-Token
              - X-Requested-With
              - Access-Control-Allow-Origin
              - X-App-Version
              - X-Device-ID
            allowCredentials: true
            maxAge: 3600  # Cache preflight response in 1 hour

# Eureka client configuration
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE}
    healthcheck:
      enabled: true
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
    hostname: localhost
    lease-renewal-interval-in-seconds: 5  # Heartbeat frequency
    lease-expiration-duration-in-seconds: 60  # Expiration time if no heartbeat received
    instanceId: ${spring.application.name}:${server.port}
